### ISSUE TITLE
Get games by release year or range of release years from JSON API

### ISSUE THREAD

**Issue by tonifisler** [Games-of-Switzerland/gos-server#128]
We should be able to query releases with these params:

- `http://api.gos.test/search/games?page=0&release_year=2017` for a single year
- `http://api.gos.test/search/games?page=0&release_year=2017-2020` for a range of years

**Comment by WengerK** [comment]
You already can do that. It's just another filter because of facets and the way we saved/index years.

`release_year_range[start]=2020&release_year_range[end]=2010`

http://api.gos.test/search/games?page=0&release_year_range[start]=2020&release_year_range[end]=2010

**Comment by tonifisler** [comment]
Ok perfect! Didn't see this in the tests
