### ISSUE TITLE
Add Images Styles to Elasticsearch response

### ISSUE THREAD

**Issue by WengerK** [Games-of-Switzerland/gos-server#89]
### 💬 Is your feature request related to a problem? 

Add Image Styles to ES responses.

### 🧞 Describe the solution you'd like

A New property containing all thé image style for Game Vivre Teaser image

### Sizes I need

- [x] **fixed ratio, cropped** `330x220px` and `660x440px` (for the game teaser)
- [x] **free ratio** `max-width 330px` and `max-width 660px` (for multiple images in game detail page)
- [x] **free ratio** `max-width 675px & max-height 500px` and `max-width 1350px & max-height 100px` (for unique image in game detail page)
- [x] **free ratio** `original` or `max-width 2560px & max-height 1600px` I would say... don't know if it's useful... (for big image in image slider)

**Comment by WengerK** [comment]
Please @tonifisler, may you add the image size you want to be exposed. Mamy thanks <3

**Comment by tonifisler** [comment]
### Sizes I need

- [ ] **fixed ratio, cropped** `330x220px` and `660x440px` (for the game teaser)
- [ ] **free ratio** `max-width 330px` and `max-width 660px` (for multiple images in game detail page)
- [ ] **free ratio** `max-width 675px & max-height 500px` and `max-width 1350px & max-height 100px` (for unique image in game detail page)
- [ ] **free ratio** `original` or `max-width 2560px & max-height 1600px` I would say... don't know if it's useful... (for big image in image slider)
